// generated by stringer -type=RFBFlag; DO NOT EDIT
//lint:file-ignore U1000 Generated by stringer: unused indices are expected

package rfbflags

import "fmt"

const _RFBFlag_name = "RFBFalseRFBTrue"

var _RFBFlag_index = [...]uint8{0, 8, 15}

func (i RFBFlag) String() string {
	if i >= RFBFlag(len(_RFBFlag_index)-1) {
		return fmt.Sprintf("RFBFlag(%d)", i)
	}
	return _RFBFlag_name[_RFBFlag_index[i]:_RFBFlag_index[i+1]]
}
