// Code generated by "stringer -type=RFBFlag"; DO NOT EDIT.

package rfbflags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RFBFalse-0]
	_ = x[RFBTrue-1]
}

const _RFBFlag_name = "RFBFalseRFBTrue"

var _RFBFlag_index = [...]uint8{0, 8, 15}

func (i RFBFlag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RFBFlag_index)-1 {
		return "RFBFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RFBFlag_name[_RFBFlag_index[idx]:_RFBFlag_index[idx+1]]
}
